name: 'Notify deploy ready'
description: 'Send email that deploy is doable'
inputs:
  smtp-password:
    description: 'SMTP password'
    required: true
  commit-sha:
    description: 'Commit SHA'
    required: true
  repository:
    description: 'Repository name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
